name: "Build Docker Images"
description: "Load the api and worker images stored as artifacts"
inputs:
  image_name:
    description: "Image name"
    required: true
  artifact: 
    description: "Artifact name to push the image"
  project_id: 
    description: "GCP project ID"
    required: true
  region:
    description: "GCP region"
    required: true
  
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure Docker to use gcloud CLI
      run: |
        gcloud auth configure-docker ${{ inputs.region }}-docker.pkg.dev
      shell: bash

    - name: Build image
      working-directory: ./src
      env:
        IMAGE_NAME: ${{ inputs.region }}-docker.pkg.dev/${{ inputs.project_id }}/${{ inputs.artifact }}/${{ inputs.image_name }}
      run: |
              docker build --no-cache -t ${IMAGE_NAME} .
              docker push ${IMAGE_NAME}
      shell: bash
