name: Build image APP

on:
  pull_request:
    branches:
        - dev
        - staging
        - stg
        - development
        - main 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (dev, stg, prd)'
        required: true
        type: choice
        options:
          - dev
          - stg
          - prd
      sensor_id:
        description: 'Sensor ID (1 or 2)'
        required: true
        type: choice
        options:
          - 1
          - 2

env:
  IMAGE_NAME: sensor
  ARTIFACT_REGION: europe-southwest1
  ARTIFACT: sensors
  REGISTRY: docker.pkg.dev
  TOPIC_PATH_SECRET: sensors

jobs:
  build-publish-sensors:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          if [[ "${{ inputs.environment }}" == "dev" ]]; then
            echo "PROJECT_ID=${{ secrets.DEV_GCP_PROJECT_ID }}" >> $GITHUB_ENV
            echo "IDENTITY_PROVIDER=${{ secrets.DEV_GCP_IDENTITY_PROVIDER }}" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=${{ secrets.DEV_GCP_SERVICE_ACCOUNT }}" >> $GITHUB_ENV
            echo "ARTIFACT_REGION=europe-southwest1" >> $GITHUB_ENV # or your dev region
          elif [[ "${{ inputs.environment }}" == "stg" ]]; then
            echo "PROJECT_ID=${{ secrets.STG_GCP_PROJECT_ID }}" >> $GITHUB_ENV
            echo "IDENTITY_PROVIDER=${{ secrets.STG_GCP_IDENTITY_PROVIDER }}" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=${{ secrets.STG_GCP_SERVICE_ACCOUNT }}" >> $GITHUB_ENV
            echo "ARTIFACT_REGION=europe-west3" >> $GITHUB_ENV # or your stg region
          elif [[ "${{ inputs.environment }}" == "prd" ]]; then
            echo "PROJECT_ID=${{ secrets.PRD_GCP_PROJECT_ID }}" >> $GITHUB_ENV
            echo "IDENTITY_PROVIDER=${{ secrets.PRD_GCP_IDENTITY_PROVIDER }}" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=${{ secrets.PRD_GCP_SERVICE_ACCOUNT }}" >> $GITHUB_ENV
            echo "ARTIFACT_REGION=us-central1" >> $GITHUB_ENV # or your prd region
          fi
        shell: bash

      - name: Authenticate with Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          token_format: access_token
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ARTIFACT_REGION }}-${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and Publish Docker Image
        uses: ./.github/actions/build-publish
        with:
          image_name: "${{ env.IMAGE_NAME }}${{ inputs.sensor_id }}:latest"
          artifact: "sensors"
          project_id: ${{ env.PROJECT_ID }}
          region: ${{ env.ARTIFACT_REGION }}